### ISSUE TITLE
Leaving & rejoining the survival world spawns you back in the overworld.

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/STEMCraft-Core#76]
Reported by Loki_BM in private.

**Comment by nomadjimbob** [comment]
I assume this means that if you use `/hub` from survival nether, then go through the portal it spawns you back in the overworld?

If this is the case, it is because the portal in the hub is just a myworlds teleport to the survival world. I don't think it has the ability to work out which dimension you where in and send you back there

**Comment by nomadjimbob** [comment]
Added a `/tpworld <player> <world>` which will teleport a player to their last location in a world, respecting world dimensions. The hub portal will need to be updated to use this command instead of the myworlds one. The myworlds author confirmed they have no such command

**Comment by nomadjimbob** [comment]
Updated server to use new command. Confirmed working
